/*
 * Copyright (C) 2017 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.digitalinfuzion.sunshinekotlin.data.database

import androidx.room.Entity
import androidx.room.Ignore
import androidx.room.Index
import androidx.room.PrimaryKey

import java.util.Date

/**
 * Defines the schema of a table in [Room] for a single weather
 * forecast. The date is used as an [Index] so that its uniqueness can be ensured. Indexes
 * also allow for fast lookup for the column.
 */
@Entity(tableName = "weather", indices = arrayOf(Index(value = ["date"], unique = true)))
data class WeatherEntry(
        /**
         * Makes sure the id is the primary key (ensures uniqueness), is auto generated by [Room].
         */
        @PrimaryKey(autoGenerate = true)
        val id: Int,
        var weatherIconId: Int,
        var date: Date,
        var min: Double,
        var max: Double,
        var humidity: Double,
        var pressure: Double,
        var wind: Double,
        var degrees: Double
    ) {

    /**
     * This constructor is used by OpenWeatherJsonParser. When the network fetch has JSON data, it
     * converts this data to WeatherEntry objects using this constructor.
     * @param weatherIconId Image id for weather
     * @param date Date of weather
     * @param min Min temperature
     * @param max Max temperature
     * @param humidity Humidity for the day
     * @param pressure Barometric pressure
     * @param wind Wind speed
     * @param degrees Wind direction
     */
    @Ignore
    constructor(weatherIconId: Int, date: Date, min: Double, max: Double, humidity: Double, pressure: Double, wind: Double, degrees: Double) : this(id = 0, weatherIconId = weatherIconId, date = date, min = min, max = max, humidity = humidity, pressure = pressure, wind = wind, degrees = degrees)
}
